apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-client
  namespace: cnpg-system
spec:
  commonName: barman-cloud-client
  issuerRef:
    kind: ClusterIssuer
    name: vault-pki
  secretName: barman-cloud-client-tls
  duration: 168h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth