apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: objectstore-local
spec:
  configuration:
    destinationPath: s3://backups/
    endpointURL: https://objectstore-local:9000
    endpointCA:
      name: step-ca-external-bundle
      key: ca.crt
    s3Credentials:
      accessKeyId:
        name: objectstore-local
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: objectstore-local
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
