apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: true
  datasource:
    name: DS_LOKI
    uid: loki
    type: loki
    access: proxy
    url: http://loki.grafana.svc.cluster.local:3100
    jsonData:
      tlsSkipVerify: true
      derivedFields:
        - matcherRegex: '"traceID":"(\w+)"'
          name: TraceID
          url: '${__value.raw}'
          datasourceUid: tempo
