apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - grafana_instance.yaml
  - grafana_datasource_loki.yaml
  - grafana_dashboard.yaml
  - grafana_dashboard_pgaudit.yaml
  - grafana_dashboard_node_exporter.yaml
  - grafana_dashboard_kube_state.yaml
  - grafana_dashboard_k8s_global.yaml
  - grafana_dashboard_k8s_pods.yaml
  - grafana_dashboard_k8s_events.yaml
  - grafana_dashboard_k8s_pod_logs.yaml
  - grafana_datasource_mimir_tempo.yaml
  - grafana_datasource_tempo.yaml
  - grafana_dashboard_cnpg_custom.yaml
  - grafana_dashboard_traefik_traces.yaml
