apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-readonly
  namespace: demo-db
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-approle
    kind: ClusterSecretStore
  target:
    name: demo-readonly
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: cnpg/demo/readonly
        property: username
    - secretKey: password
      remoteRef:
        key: cnpg/demo/readonly
        property: password
