apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-local-superuser
  namespace: demo-local-db
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-approle
    kind: ClusterSecretStore
  target:
    name: pg-local-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: pg-local/superuser
        property: username
    - secretKey: password
      remoteRef:
        key: pg-local/superuser
        property: password
