server = "https://registry-1.docker.io"

[host."https://zot.172-18-0-250.sslip.io/v2/docker.io"]
  capabilities = ["pull", "resolve"]
  override_path = true
  ca = "/etc/containerd/certs.d/step-ca-chain.pem"
