apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-rbr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rbr
  source:
    repoURL: https://github.com/rmlandvreugd/cnpg-playground.git
    targetRevision: vault
    path: manifests
    directory:
      include: 'capsule-tenant-rbr.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
