{{- if .Values.observability.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.observability.metrics.path }}
      interval: 15s
{{- end }}
