{{- if and .Values.externalSecret.enabled (eq .Values.database.credentialsMode "dynamic") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.passwordSecret }}-dynamic
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  refreshInterval: {{ .Values.database.dynamicSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.database.passwordSecret }}
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.database.dynamicSecret.vaultPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.database.dynamicSecret.vaultPath }}
        property: password
{{- end }}
