apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verstappen-app
  namespace: rbr-ver-db
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-approle-rbr
    kind: ClusterSecretStore
  target:
    name: verstappen-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: rbr/ver/app
        property: username
    - secretKey: password
      remoteRef:
        key: rbr/ver/app
        property: password
