replicaCount: 1

image:
  tag: "dev"
  pullPolicy: Always

app:
  debug: true
  logLevel: "DEBUG"

migration:
  strategy: "startup"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

tls:
  hostnamePrefix: "demo-dev-demo"
